### ISSUE TITLE
Sonarr NTFY Script Update

### ISSUE THREAD

**Issue by Joeharrison94** [nickexyz/ntfy-shellscripts#1]
![image](https://user-images.githubusercontent.com/53116754/158762741-95b78648-d575-4e7a-806d-ce23da941404.png)

This is the error ^^^^ that Sonarr and the rest of the Arr family throw when you try to add the script templates, to avoid this I have found that you need to add event handling for testing as below. Please add this into your scripts :).

```
#!/usr/bin/env bash

ntfy_url="https://example.com/topic"
ntfy_username="CHANGEME"
ntfy_password="CHANGEME"

ntfy_title="$sonarr_series_title"
ntfy_message=" "
############################################################added vvvv
if [ "$sonarr_eventtype" == "Test" ]; then
  exit 0
############################################################changed to elif from if vvvv
elif [ "$sonarr_eventtype" == "Download" ]; then
  ntfy_tag=tv
  ntfy_title+=" - S"
  ntfy_title+="$sonarr_episodefile_seasonnumber"
  ntfy_title+=":E"
  ntfy_title+="$sonarr_episodefile_episodenumbers"
  ntfy_message+="- "
  ntfy_message+="$sonarr_episodefile_episodetitles"
  ntfy_message+=" ["
  ntfy_message+="$sonarr_episodefile_quality"
  ntfy_message+="]"
elif [ "$sonarr_eventtype" == "HealthIssue" ]; then
  ntfy_tag=warning
  ntfy_message+="$sonarr_health_issue_message"
else
  ntfy_tag=information_source
fi

curl -u $ntfy_username:$ntfy_password -H "tags:"$ntfy_tag -H "Click: https://www.thetvdb.com/?id=""$sonarr_series_tvdbid""&tab=series" -H "X-Title: Sonarr: $sonarr_eventtype" -d "$ntfy_title""$ntfy_message" --request POST $ntfy_url
```

**Comment by Joeharrison94** [comment]
Also here is a script for Prowlarr.

```

#!/usr/bin/env bash

ntfy_url="https://example.com/topic"
ntfy_username="CHANGEME"
ntfy_password="CHANGEME"

ntfy_title="Prowlarr Issue - $prowlarr_health_issue_type"
ntfy_message=" "
if [ "$prowlarr_eventtype" == "Test" ]; then
  exit 0
elif [ "$prowlarr_eventtype" == "HealthIssue" ]; then
  ntfy_tag=warning
  ntfy_message+="$prowlarr_health_issue_message"
fi

curl -u $ntfy_username:$ntfy_password -H "tags:"$ntfy_tag -H "X-Title: Prowlarr: $prowlarr_eventtype" -d "$ntfy_title"\n"$ntfy_message" --request POST $ntfy_url
```

**Comment by Joeharrison94** [comment]
> Hm, I can't seem to replicate the error. Not sure what would cause an exit code 2 in the script. Do you still get the same error if you just end the script with exit 0? (exit 0 on the last line, after curl.)
> 
> if [ "$sonarr_eventtype" == "Test" ]; then
>   exit 0
> Would work, but then you don't get the test push notification. Which probably isn't a huge deal though.
> 
> Thanks for the Prowlarr script! Is it OK if I include it in the collection?

Sonarr v3 wouldn't let me save it without testing it so I included the test event to just exit 0 and yeah sure no problem :)

**Comment by Joeharrison94** [comment]
I've also got some others some are niche use cases and other are In other languages like powershell

**Comment by nickexyz** [comment]
I'm running 3.0.7.1479 of Sonarr myself, and that seems to work for me. Not using a prebuilt container though, maybe that has something to do with it.

But if an exit 0 fixes the issue, I'll add it to the scripts. :)

**Comment by Joeharrison94** [comment]
Yep it works a treat

**Comment by nickexyz** [comment]
Done and done!

**Comment by Joeharrison94** [comment]
If you need or want any of my other ones let me know

**Comment by nickexyz** [comment]
Sure, one can never get too many ways to get notifications!
