### ISSUE TITLE
Sonarr/Radarr on download changed to on grab

### ISSUE THREAD

**Issue by cowbe0x004** [nickexyz/ntfy-shellscripts#10]
Looks like "Download" notification trigger is no longer available, it's changed to "On Grab" instead.
![image](https://github.com/nickexyz/ntfy-shellscripts/assets/3072913/f23f4799-3254-4b37-be88-c0bbfd40505b)

I updated the script from Download to Grab and seems to be working fine. 

Though I'm not sure where this icon is specified, it's not $radarr_ntfy_icon, any idea?
![image](https://github.com/nickexyz/ntfy-shellscripts/assets/3072913/64cb5ff9-3b3a-4fb6-8c3b-07dbf79115e9)

EDIT: found the answer,
![image](https://github.com/nickexyz/ntfy-shellscripts/assets/3072913/bb8aa9df-bd32-4bc7-b7d6-0393058b2b36)

**Comment by nickexyz** [comment]
Sorry for not replying earlier, I missed that there was an issue.

Thanks for the information, I'll change the script asap!
Seems weird to remove "On download". I'm guessing that "On grab" is when the download starts, not the same thing.
But, it is what it is I guess. :)

**Comment by nickexyz** [comment]
I added the eventtype Grab, but left Download. Hopefully it will come back at some point.

Thanks for pointing out the issue! #
