### ISSUE TITLE
Sonarr v3.0.10.1567, Script exited with code: 6

### ISSUE THREAD

**Issue by zackchadwick** [nickexyz/ntfy-shellscripts#3]
I'm currently receiving an error of "Script exited with code: 6" when attempting to run the Test for the Sonarr script. Sonarr is on version 3.0.10.1567.

I have also tried removing the "Test" portion per another issue, but do not receive any notifications even after successfully (not really, since Test check is gone) saving the notifications.

Sonarr is deployed via the linuxserver.io container on a kubernetes cluster. Ntfy is also running in my cluster. Notification tie in with Radarr works (the native one, not using the script).

**Comment by nickexyz** [comment]
I'm guessing since I'm not using linuxserver, but could curl be missing from the container?

Try running the script manually from the container, that might give some clues what might be wrong.

**Comment by zackchadwick** [comment]
Thanks nickexys, not sure why I didn't think of that. Looks like curl is installed in the container but the container is having an issue resolving the internal DNS for ntfy.

This points me in the right direction, much appreciated.

**Comment by zackchadwick** [comment]
....it was of course a typo in the URL.
